### ISSUE TITLE
RxJava Usage ?

### ISSUE THREAD

**Issue by Muhammadwahab** [mayuroks/android-mvp-realtime-chat#1]
Hi **Mayur Rokade** First of all i will thanks you for this great tutorial on MVP Real time app.This is not a issue but did not found any usage of RxJava in this app.Why you use RXJava in this app ?

**Comment by mayuroks** [comment]
Hi @Muhammadwahab. RxJava is definitely used here.

For async network tasks like sending a message to server, we need RxJava to send a message and wait for server to give back acknowledgement.

We also need observer callbacks like onSuccess, onError, onCompleted to handle the acknowledgement. That's why RxJava is used. 

Since this is a small app and to keep examples concise, there is only one usage of RxJava in the app.

You can see the example below from the code.
```java
    /**
     * Send chat message to the server.
     *
     * @param chatMessage
     * @return
     */
    @Override
    public Flowable<ChatMessage> sendMessage(@NonNull final ChatMessage chatMessage) {
        return Flowable.create(new FlowableOnSubscribe<ChatMessage>() {
            @Override
            public void subscribe(FlowableEmitter<ChatMessage> emitter) throws Exception {
                mSocket.emit(EVENT_NEW_MESSAGE, chatMessage.getMessage());
                emitter.onNext(chatMessage);
            }
        }, BackpressureStrategy.BUFFER);
    }
```

This snippet is from [EventServiceImpl.java](https://github.com/mayuroks/android-mvp-realtime-chat/blob/master/app/src/main/java/com/mayurrokade/chatapp/eventservice/EventServiceImpl.java#L113-L146)
